### ISSUE TITLE
Node.js, activemq, binary body

### ISSUE THREAD

**Issue by kum-deepak** [stomp-js/stompjs#113]
Reported by @parmy, extracted from #22 

Hi

Thanks for providing a great library, even though I haven't quite got it to work yet.

I'm hoping to connect to a ActiveMQ server, which will send GZIP messages.

I tried:

https://github.com/easternbloc/node-stomp-client
Following an article I read here:
https://medium.com/@mackplevine/using-activemq-with-node-js-stomp-and-http-b251ce8d995

I manage to connect to the client using the package, with the following:

---
```javascript
	var options = {
		address: 	        'some url',
		port: 		'61613',
		user: 		'username',
		pass: 		'password',
		protocolVersion: '1.0' <-- could also be '1.1'
	}

var stompClient = new require('stomp-client')(options);

stompClient.connect(function(sessionId) {
    	stompClient.subscribe('/topic/...', function(body, headers) {
        }
})
```

---

I manage to make a connection and it's stable. However, without a major overhaul the stomp-client project cannot process message bodies which are sent compressed (gzip).

I came across your library, which appears to handle binary messages. However, I'm unable to connect to the ActiveMQ server.

Here's my attempt:
```javascript
	var client = StompJs.Stomp.over(options["address"] + ":" + options["port"]);

	client.connect(options["user"], options["pass"], 
		function(e) {
			//connect
			console.log(e);
		}, function(err) {
			//error
			console.log(err);
		}, function(e) {
			//close
			console.log(e);
		}
	);
```

I've tried various things options with address, prefixing it with "ws://" and without. stomp-client didn't require "ws://".

I'm running this in a node client and I get the following error message:

```javascript
Opening Web Socket...
(node:3858) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'binaryType' on string 'darwin-dist-44ae45.nationalrail.co.uk:61613'
    at CompatClient../src/client.ts.Client._createWebSocket (...app/index/node_modules/@stomp/stompjs/bundles/stomp.umd.js:422:30)
    at CompatClient.<anonymous> (...app/index/node_modules/@stomp/stompjs/bundles/stomp.umd.js:361:48)
    at step (...app/index/node_modules/@stomp/stompjs/bundles/stomp.umd.js:165:23)
    at Object.next (...app/index/node_modules/@stomp/stompjs/bundles/stomp.umd.js:146:53)
    at fulfilled (...app/index/node_modules/@stomp/stompjs/bundles/stomp.umd.js:137:58)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:3858) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3858) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When I try 

var client = StompJs.Stomp.client(options["address"] + ":" + options["port"]);

I get the following error:

"(node:4111) UnhandledPromiseRejectionWarning: ReferenceError: WebSocket is not defined"

I can confirm I've installed websocket using npm. 

Any suggestions please?

Thank you.

**Comment by kum-deepak** [comment]
Please read https://stomp-js.github.io/guide/stompjs/2018/06/28/using-stompjs-v5.html on usage of this library. This library is different than node-stomp-client in one sense that it does not use TCP as underlying transport (it uses WebSockets instead). So, you will need to enable WebSocket support at the broker.

On the other hand, when using node you are not restricted to using STOMP for connectivity. You may try MQTT or AMQP as well.
