### ISSUE TITLE
issue in nodejs.(node:5465) UnhandledPromiseRejectionWarning: ReferenceError: WebSocket is not defined

### ISSUE THREAD

**Issue by windontheair1991** [stomp-js/stompjs#151]
(node:5465) UnhandledPromiseRejectionWarning: ReferenceError: WebSocket is not defined
    at Client../src/client.ts.Client._createWebSocket (/Users/matt.miao/Documents/otc/SocketTest/ts-express/node_modules/@stomp/stompjs/bundles/stomp.umd.js:419:13)
    at Client.<anonymous> (/Users/matt.miao/Documents/otc/SocketTest/ts-express/node_modules/@stomp/stompjs/bundles/stomp.umd.js:359:48)
    at step (/Users/matt.miao/Documents/otc/SocketTest/ts-express/node_modules/@stomp/stompjs/bundles/stomp.umd.js:165:23)
    at Object.next (/Users/matt.miao/Documents/otc/SocketTest/ts-express/node_modules/@stomp/stompjs/bundles/stomp.umd.js:146:53)
    at fulfilled (/Users/matt.miao/Documents/otc/SocketTest/ts-express/node_modules/@stomp/stompjs/bundles/stomp.umd.js:137:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by kum-deepak** [comment]
Node.js needs certain polyfills, please see https://stomp-js.github.io/guide/stompjs/rx-stomp/ng2-stompjs/2018/06/29/pollyfils-for-stompjs-v5.html
