### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Digister** [stomp-js/stompjs#26]
After doing all the necessary steps in the usage instructions section, only requiring stompJs leads to an error:
abc.js: 
const WebSocket = require('websocket').w3cwebsocket;
const StompJs = require('@stomp/stompjs');

$ node abc.js
c:\Users\....\Desktop\node_test\node_modules\@stomp\stompjs\bundles\stomp.umd.js:10
})(window, function() {
   ^
ReferenceError: window is not defined
    at Object.<anonymous> (c:\Users\....\Desktop\node_test\node_modules\@stomp\stompjs\bundles\stomp.umd.js:10:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\Users\....\Desktop\node_test\abc.js:2:17)
    at Module._compile (module.js:652:30)

**Comment by kum-deepak** [comment]
Please change it to:

```javascript
const WebSocket = require('websocket').w3cwebsocket;
const StompJs = require('@stomp/stompjs/esm5');
```

I will update the instructions as well.

**Comment by kum-deepak** [comment]
Updated instructions at https://stomp-js.github.io/guide/stompjs/2018/06/28/using-stompjs-v5.html

Thanks for pointing out 😄

**Comment by kum-deepak** [comment]
https://github.com/webpack/webpack/issues/6525#issuecomment-417580843 seems to resolve the issue. It will be released as part of 5.1
