### ISSUE TITLE
Uhandled Frame with ActiveMQ Artemis

### ISSUE THREAD

**Issue by oceanofmaya** [stomp-js/stompjs#286]
I see the log that it connected, onConnect is never called and I see that the onUnhandledFrame is called. I'm running artemis locally for debugging and curious what could be wrong.

```
  console.log
    STOMP: Opening Web Socket...
      at Client.debug (src/service/message-service.ts:35:17)

  console.log
    STOMP: Web Socket Opened...
      at StompHandler.debug (src/service/message-service.ts:35:17)

  console.log
    STOMP: >>> CONNECT
    accept-version:1.0,1.1,1.2
    heart-beat:4000,4000
      at StompHandler.debug (src/service/message-service.ts:35:17)

  console.log
    STOMP: Received data
      at StompHandler.debug (src/service/message-service.ts:35:17)

  console.log
    STOMP: <<< CONNECTED
    version:1.2
    session:73c7da2c
    server:ActiveMQ-Artemis/2.4.0.amq-710004-redhat-1 ActiveMQ Artemis Messaging Engine
    heart-beat:4000,4000
      at StompHandler.debug (src/service/message-service.ts:35:17)

  console.log
    Unhandled frame FrameImpl {
      command: '',
      headers: { '': '' },
      _binaryBody: Uint8Array(0) [],
      isBinaryBody: true,
      escapeHeaderValues: false,
      skipContentLengthHeader: false
    }
      at Client.onUnhandledFrame (src/service/message-service.ts:57:17)

  console.log
    STOMP: <<< PONG
      at StompHandler.debug (src/service/message-service.ts:35:17)

  console.log
    STOMP: Received data
      at StompHandler.debug (src/service/message-service.ts:35:17)

  console.log
    STOMP: <<<
      at StompHandler.debug (src/service/message-service.ts:35:17)

  console.log
    STOMP: <<< PONG
      at StompHandler.debug (src/service/message-service.ts:35:17)

 console.log
    STOMP: Connection closed to tcp://localhost:61616
	  at StompHandler.debug (src/service/message-service.ts:35:17)
```

Artemis logs also confirms that STOMP connection occurred and was closed after the stomp client closed it.

```
2020-10-06 19:27:27,635 DEBUG [org.apache.activemq.artemis.core.server] Setting STOMP client TTL to: 8000
2020-10-06 19:27:32,569 WARN  [org.apache.activemq.artemis.core.server] AMQ222067: Connection failure has been detected: null [code=REMOTE_DISCONNECT]
```

**Comment by oceanofmaya** [comment]
Based on my understanding it appears the frame Artemis sent in response to the CONNECT command ended becoming an unhandled frame, so even though the connection was successful, it ended there. If that is the case what can I do to remedy this?

**Comment by kum-deepak** [comment]
Please check that you are connecting to the WebStomp endpoint of ActiveMQ. See https://activemq.apache.org/components/artemis/documentation/latest/stomp.html#web-sockets.

Your WebSocket URL should start with 'ws:'

If that does not help, please share your Stomp and ActiveMQ configurations.

**Comment by kum-deepak** [comment]
BTW I saw your website, lovely photographs :+1:

**Comment by oceanofmaya** [comment]
Thank you. I have tried with ws:// as well and I get the same behavior where the onConnect isn't called and it goes to onUnHandledFrame. 

Do note if I put the subscribe inside the onUnhandledFrame to test, it works and I'm successful in creating a durable subscription and able to receive the message even though the callback was not called.

Additionally, I have confirmed that STOMP works with the test chat example provided by artemis and I can successfully connect to both ws://localhost:61613 and ws://localhost:61616

Publish seems to work and I see the message sent to the topic arrive both in my subscription within the code and also in the test chat example that I'm running while connected to the same topic.

Below are my acceptors for artemis and I have STOMP enabled for both ports 
![image](https://user-images.githubusercontent.com/33257049/95351044-c9443200-088e-11eb-91bb-00d6f4d70883.png)

Here is the stripped out base code I'm using
```
import { Client } from "@stomp/stompjs";

/* eslint-disable */
Object.assign(global, { WebSocket: require("ws") });
declare const TextEncoder: any;

export class MessageService {
  private _client: Client;

  constructor() {
    if (typeof TextEncoder !== "function") {
      const TextEncodingPolyfill = require("text-encoding");
      Object.assign(global, { TextEncoder: TextEncodingPolyfill.TextEncoder });
      Object.assign(global, { TextDecoder: TextEncodingPolyfill.TextDecoder });
    }

    // create client
    this._client = new Client();
    // set some default configurations
    this._client.configure({
      brokerURL: "ws://localhost:61613", 
      debug: function (str) {
        // remove for prod as it can print sensitive info
        console.log("STOMP: " + str);
      },
      connectHeaders: { "client-id": "one" },
      logRawCommunication: true,
      reconnectDelay: 5000,
      heartbeatIncoming: 4000,
      heartbeatOutgoing: 4000,
      onConnect: (frame) => {
        console.log("Connected successfully", frame);
        // Use this callback on the client
        // All subscribers must be done in this callback
        // This is needed because this will be executed after a reconnect

        this._client.subscribe(
        destination,
        (message) => {
          console.log("I read it", message);
        },
        { id: "sub01", "durable-subscription-name": "sub-name" },
      );
      },
      onStompError: (frame) => {
        // Will be invoked in case of error encountered at Broker
        // Bad login/passcode typically will cause an error
        // Complaint brokers will set `message` header with a brief message. Body may contain details.
        // Compliant brokers will terminate the connection after any error
        console.log("Broker reported error", frame.headers["message"]);
        console.log("Additional details ", frame.body);
      },
      onUnhandledFrame: (frame) => {
        console.log("Unhandled frame", frame);
      },
    });

    this._client.activate();
  }
```

**Comment by kum-deepak** [comment]
I have not used ActiveMQ myself. Please send me your ActiveMQ config file, I will install it locally and test.

**Comment by oceanofmaya** [comment]
This the broker (AMQ 7.1.0 Broker) I'm using as that is version the place I work at uses. You can download it from here and install locally https://developers.redhat.com/products/amq/download

The default configuration for local use will have all of the acceptors I mentioned earlier, here is a snippet
```
<acceptors>

         <!-- useEpoll means: it will use Netty epoll if you are on a system (Linux) that supports it -->
         <!-- amqpCredits: The number of credits sent to AMQP producers -->
         <!-- amqpLowCredits: The server will send the # credits specified at amqpCredits at this low mark -->

         <!-- Acceptor for every supported protocol -->
         <acceptor name="artemis">tcp://0.0.0.0:61616?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=CORE,AMQP,STOMP,HORNETQ,MQTT,OPENWIRE;useEpoll=true;amqpCredits=1000;amqpLowCredits=300</acceptor>

         <!-- AMQP Acceptor.  Listens on default AMQP port for AMQP traffic.-->
         <acceptor name="amqp">tcp://0.0.0.0:5672?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=AMQP;useEpoll=true;amqpCredits=1000;amqpMinCredits=300</acceptor>

         <!-- STOMP Acceptor. -->
         <acceptor name="stomp">tcp://0.0.0.0:61613?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=STOMP;useEpoll=true</acceptor>

         <!-- HornetQ Compatibility Acceptor.  Enables HornetQ Core and STOMP for legacy HornetQ clients. -->
         <acceptor name="hornetq">tcp://0.0.0.0:5445?protocols=HORNETQ,STOMP;useEpoll=true</acceptor>

         <!-- MQTT Acceptor -->
         <acceptor name="mqtt">tcp://0.0.0.0:1883?tcpSendBufferSize=1048576;tcpReceiveBufferSize=1048576;protocols=MQTT;useEpoll=true</acceptor>

      </acceptors>
```

**Comment by kum-deepak** [comment]
Please add the following to your acceptors and try:

```
<acceptor name="stomp-ws-acceptor">tcp://0.0.0.0:61614?protocols=STOMP</acceptor>
```

I have downloaded the latest Artemis and tested with the above using `ws://localhost:61614` as the broker URL.

Older versions (<= v4), supported STOMP over TCP. From v5 this library only supports STOMP over Websockets. It seems Artemis bundles older version (probably v2 or v3) of this library - that explains why their chat example works.

**Comment by oceanofmaya** [comment]
Thank you for getting back to me so quickly. I appreciate it.

I tried with the above acceptor; it is similar to the existing acceptors for STOMP but without tcpSendBufferSize and tcpReceiveBuffer size and I'm still getting the problem behavior with the version of Artemis I'm using.

So you are saying either I have to use the later version of Artemis or use the older version of you library

**Comment by kum-deepak** [comment]
I am not sure if I understand correctly. Both acceptors are not the same - `stomp` vs `stomp-ws-acceptor`.

I also tested with artemis 2.14 which seems your version with your code, the following is the output:

```
STOMP: Opening Web Socket...
STOMP: Web Socket Opened...
STOMP: >>> CONNECT
client-id:one
accept-version:1.0,1.1,1.2
heart-beat:4000,4000


STOMP: Received data
STOMP: <<< CONNECTED
version:1.2
session:4f1105fb
server:ActiveMQ-Artemis/2.14.0 ActiveMQ Artemis Messaging Engine
heart-beat:4000,4000



STOMP: connected to server ActiveMQ-Artemis/2.14.0 ActiveMQ Artemis Messaging Engine
STOMP: send PING every 4000ms
STOMP: check PONG every 4000ms
Connected successfully FrameImpl {
  command: 'CONNECTED',
  headers: {
    'heart-beat': '4000,4000',
    server: 'ActiveMQ-Artemis/2.14.0 ActiveMQ Artemis Messaging Engine',
    session: '4f1105fb',
    version: '1.2'
  },
  _binaryBody: Uint8Array(0) [],
  isBinaryBody: true,
  escapeHeaderValues: false,
  skipContentLengthHeader: false
}
STOMP: >>> SUBSCRIBE
id:sub01
durable-subscription-name:sub-name
destination:chat


STOMP: <<< PONG
STOMP: Received data
STOMP: <<< 

STOMP: <<< PONG
STOMP: >>> PING
STOMP: Received data
STOMP: <<< 

STOMP: <<< PONG
STOMP: >>> PING
STOMP: Received data
STOMP: <<< 
```

**Comment by kum-deepak** [comment]
At this point, I can only suggest that you try your code with latest version of node, artemis (from Apache Website), this libary and see if works. From that point you can downgrade one at a time to check what causes it to fail.

**Comment by oceanofmaya** [comment]
Thank you once again for the assistance. I truly appreciate it. Unfortunately I need it to with that specific broker.

Based on your logs it appears that the connected frame that is received in my case is missing the command CONNECTED (and headers I had sent I passed in CONNECT), which is likely the reason why it is ending up as unhandled frame.

I ended up trying another library (stompit) and it seems to work. It also has a feature to take in an array of servers, choose randomly and use as failover, which in my case is desirable as the infrastructure I'm coding for is clustered.

**Comment by oceanofmaya** [comment]
Since this doesn't really appear to be an issue with the library itself and is resolved with a later version of artemis ActiveMQ, I will close it. Thank you for your help.
