### ISSUE TITLE
Error while sending heartbeat

### ISSUE THREAD

**Issue by vidastoleikis** [stomp-js/stompjs#57]
An error in sending heartbeat breaks the whole process. It would be great if this could be handled. It happens then server drop session and client try to send heartbeat to server. In my case I want possibility to schedule a reconnect when this happens or this can be done by default.

```
...\node_modules\websocket\lib\W3CWebSocket.js:113
        throw new Error('cannot call send() while not connected');
        ^

Error: cannot call send() while not connected
    at W3CWebSocket.send (...\node_modules\websocket\lib\W3CWebSocket.js:113:15)
    at Timeout._onTimeout (...\node_modules\@stomp\stompjs\esm5\stomp-handler.js:162:34)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by vidastoleikis** [comment]
Everything works fine with a additional check. Thanks!
